[phases.setup]
nixPkgs = ["python312", "nodejs_20"]

[phases.install]
depends = ["setup"]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install -r requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
depends = ["install"]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "/opt/venv/bin/python run.py"
